site_name: Orlando Repair Cafe
site_description: Documentation for Orlando Repair Cafe organization
site_author: Orlando Repair Cafe
site_url: https://orlando-repair-cafe.github.io/landing-page/

repo_name: Orlando-Repair-Cafe/landing-page
repo_url: https://github.com/Orlando-Repair-Cafe/landing-page

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

nav:
  - Home: index.md
  - About: about.md
  - Getting Involved: getting-involved.md
